server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    include /etc/nginx/mime.types;
    types {
        application/javascript js mjs;
    }

    location /rn-codex/ {
        try_files $uri $uri/ /rn-codex/index.html;
    }

    location / {
        return 301 /rn-codex/;
    }
}
